### ISSUE TITLE
error while trying to read hook -- Could not find namespace: clojure.pprint.

### ISSUE THREAD

**Issue by escherize** [borkdude/carve#67]
I was investigating using this on the Metabase codebase, but got this error / stack trace.

`carve --opts '{:paths ["src" "test"] :report {:format :text}}'`

```
$ carve --opts '{:paths ["src" "test"] :report {:format :text}}'
WARNING: file clojure/pprint.clj not found while loading hook
WARNING: error while trying to read hook for metabase.models.setting/defsetting: Could not find namespace: clojure.pprint.
Exception in thread "main" java.lang.NullPointerException
	at clojure.core$namespace.invokeStatic(core.clj:1605)
	at clojure.core$namespace.invoke(core.clj:1599)
	at carve.impl$ignore_QMARK_.invokeStatic(impl.clj:183)
	at carve.impl$ignore_QMARK_.invoke(impl.clj:176)
	at carve.impl$do_run_BANG_$fn__18981.invoke(impl.clj:260)
	at clojure.core$complement$fn__5687.invoke(core.clj:1443)
	at clojure.core$filter$fn__5912.invoke(core.clj:2825)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5420.invokeStatic(core.clj:139)
	at clojure.core$map$fn__5885.invoke(core.clj:2750)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:713)
	at clojure.core$next__5404.invokeStatic(core.clj:64)
	at clojure.core$reduce1.invokeStatic(core.clj:946)
	at clojure.core$set.invokeStatic(core.clj:4101)
	at clojure.core$set.invoke(core.clj:4093)
	at carve.impl$do_run_BANG_.invokeStatic(impl.clj:262)
	at carve.impl$do_run_BANG_.invoke(impl.clj:222)
	at carve.impl$run_PLUS_.invokeStatic(impl.clj:344)
	at carve.impl$run_PLUS_.invoke(impl.clj:337)
	at carve.api$carve_BANG_.invokeStatic(api.clj:36)
	at carve.api$carve_BANG_.invoke(api.clj:25)
	at carve.main$main.invokeStatic(main.clj:12)
	at carve.main$main.doInvoke(main.clj:7)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$apply.invoke(core.clj:662)
	at carve.main$_main.invokeStatic(main.clj:16)
	at carve.main$_main.doInvoke(main.clj:14)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at carve.main.main(Unknown Source)
```

**Comment by borkdude** [comment]
We need to update the bundled clj-kondo which has support for that. I'll do that after the next clj-kondo release

**Comment by borkdude** [comment]
You can still use the JVM carve library and bump clj-kondo yourself for now

**Comment by borkdude** [comment]
You can try it with babashka instead for now, I just made carve compatible:

```
bb -Sdeps '{:deps {io.github.borkdude/carve {:git/sha "c8b12536527b5bd3da6ad4f3084122dbc36dfbc8"}}}' -x carve.api/carve! --paths src
```

I'll make a proper release next week or in the weekend.

**Comment by escherize** [comment]
This workaround works well. Thanks!
